config/routes.rb
Certificatec::Application.routes.draw do
  root :to => 'splash#index'
  
  match '/login' => 'splash#login', :as => 'login'
  match '/logout' => 'splash#logout', :as => 'logout'
  match 'splash/authenticate' => 'splash#authenticate', :via => :post
  match '/cursos' => 'courses#index', :as => 'courses'
  match '/fechas' => 'courses#agenda', :as => 'agenda'
  match '/inscripcion/:group_id' => 'courses#enroll', :as => 'enroll'
  match '/contacto' => 'splash#contact', :as => 'contact'
  
  resources :students, :only => :create
  
  namespace :admin do 
    root :to => 'courses#index'
    
    resources :courses do
      resources :course_dates
      resources :exams
    end
    resources :groups
    resources :users
  end
end

app/models/exam.rb
class Exam < ActiveRecord::Base

  belongs_to :course
  belongs_to :group

  validates_presence_of :date, :location  
  
  scope :upcoming, where('date > ?', Time.now).order(:date)
  
  def minutes
    self.date.min if self.date
  end
  
  def minutes=(minutes)
    self.date = self.date.change(:min => minutes)
  end
  
  def hour
    self.date.hour if self.date
  end
  
  def hour=(hour)
    self.date = self.date.change(:hour => hour)
  end
end

app/controllers/admin/exams_controller.rb
class Admin::ExamsController < Admin::SharedController
  before_filter :get_course
  
  # GET /admin/courses/:course_id/exams
  def index 
    @exams = @course.exams.paginate(:page => params[:page]).order('date DESC')
  end
  
  # GET /admin/courses/:course_id/exams/:id
  def show
    @exam = @course.exams.find(params[:id])
  end
  
  # GET /admin/courses/:course_id/exams/new
  def new
    @exam = @course.exams.build
    @groups = Group.order(:name)
    render 'form'
  end
  
  # POST /admin/courses/:course_id/exams.json
  def create
    @exam = @course.exams.build(params[:exam])
    @exam.save
    
    respond_to do |format|
      format.json { render json: { errors: @exam.errors, url: admin_course_exams_url(@course) } }
    end
  end
  
  # GET /admin/courses/:course_id/exams/edit
  def edit
    @exam = @course.exams.find(params[:id])
    @groups = Group.order(:name)
    render 'form'    
  end
  
  # PUT /admin/courses/:course_id/exams/:id.json
  def update
    @exam = @course.exams.find(params[:id])
    @exam.update_attributes(params[:exam])
    
    respond_to do |format|
      format.json { render json: { errors: @exam.errors, url: admin_course_exams_url(@course) } }
    end
  end
  
  # DELETE /admin/courses/:course_id/exams/:id.json
  def destroy
    @exam = @course.exams.find(params[:id])
    
    respond_to do |format|
      format.json { render json: { deleted: @exam.destroy } }
    end
  end
  
  protected
    def get_course
      @course = Course.active.find(params[:course_id])       
    end
end

app/helpers/admin/exams_helper.rb
module Admin::ExamsHelper
end

app/views/admin/exams/form.html.erb
<% content_for :head do %>
  <%= javascript_include_tag 'admin/shared/section_form' %>
  <%= javascript_include_tag 'admin/exams/form' %>
<% end %>
<div class="content-wrapper">
  <div id="section-actions">
    <div class="left">
      <h2><%= @exam.new_record? ? 'Agregar Registro' : 'Editar Registro' %></h2>
    </div>
    <div class="right">
      <%= link_to admin_course_exams_url(@course), :class => 'btn gray-btn' do %>
          Cancelar
      <% end %>
    </div>  
    <div class="clear"></div>
  </div>
  <div class="form-wrapper section-form-wrapper">
    <%= form_for [:admin, @course, @exam], :html => {:id => 'section-form',:class => 'custom-form section-form'} do |f| %>
      <div class="field">
        <%= f.label :date, 'Fecha' %>
        <%= f.text_field :date, :value => (@exam.new_record? ? '' : slash_format(@exam.date) ) %>
      </div>
      <div class="field">
        <label>Hora</label>
        <%= f.select :hour, hour_options %>:<%= f.select :minutes, minute_options %>
      </div>
      <div class="field">
        <%= f.label :group_id, 'Grupo' %>
        <%= f.select :group_id, group_options(@groups), {:prompt => 'Seleccione'}, {:class => 'wide'} %>
      </div>
      <div class="field">
        <%= f.label :location, 'Ubicaci&oacute;n'.html_safe %>
        <%= f.text_area :location %>
      </div>
      <div class="actions">
        <%= f.submit 'Continuar', :class => 'btn green-btn' %>
      </div>
    <% end %>    
  </div>
</div>

app/views/admin/exams/index.html.erb
<div class="content-wrapper">
  <div id="section-actions">
    <div class="left">
      <h2><%= truncate @course.name, :length => 50 %></h2>
    </div>
    <div class="right">
      <%= link_to admin_courses_url, :class => 'btn gray-btn' do %>
        Regresar
      <% end %> 
      <%= link_to new_admin_course_exam_url(@course), :class => 'btn green-btn' do %>
        <i class="icon-plus"></i> Agregar
      <% end %>
    </div>  
    <div class="clear"></div>
  </div>
  <% if @exams.any? %>
    <div class="table-wrapper">
      <table class="custom-table">
        <thead>
          <tr>
            <th>Fecha</th>
            <th>Hora</th>            
            <th>Ubicaci&oacute;n</th>            
            <th>Grupo</th>            
            <th></th>        
            <th></th>
          </tr>        
        </thead>
        <tbody>
          <% @exams.each_with_index do |exam,index| %>
            <%= render_table_row(index) do %>
              <td><%= slash_format exam.date %></td>
              <td><%= time_format exam.date %></td>
              <td><%= truncate exam.location, :length => 100 %></td>
              <td><%= exam.group ? exam.group.name : "Sin asignar" %></td>
              <td class="action">
                <%= link_to edit_admin_course_exam_url(@course, exam), 'data-tooltip' => 'Editar' do %>
                  <i class="icon-pencil"></i>
                <% end %>
              </td>
              <td class="action">
                <%= link_to admin_course_exam_url(@course, exam), 'data-tooltip' => 'Eliminar', 'data-method' => 'delete' do %>
                  <i class="icon-remove"></i>
                <% end %>
              </td>
            <% end %>
          <% end %>
        </tbody>
      </table>
    </div>  
    <%= paginate @exams %>  
  <% else %>
    <div class="not-found">
      No hay ex&aacute;menes
    </div>
  <% end %>
</div>