config/routes.rb
Certificatec::Application.routes.draw do
  root :to => 'splash#index'
  
  match '/login' => 'splash#login', :as => 'login'
  match '/logout' => 'splash#logout', :as => 'logout'
  match 'splash/authenticate' => 'splash#authenticate', :via => :post
  match '/cursos' => 'courses#index', :as => 'courses'
  match '/fechas' => 'courses#agenda', :as => 'agenda'
  match '/inscripcion/:group_id' => 'courses#enroll', :as => 'enroll'
  match '/contacto' => 'splash#contact', :as => 'contact'
  
  resources :students, :only => :create
  
  namespace :admin do 
    root :to => 'courses#index'
    
    resources :courses do
      resources :course_dates
      resources :exams
    end
    resources :groups
    resources :users
  end
end

app/models/course_date.rb
class CourseDate < ActiveRecord::Base
  belongs_to :group
  belongs_to :course
  
  scope :upcoming, where('date > ?', Date.today).order(:date)
  
end

app/controllers/admin/course_dates_controller.rb
class Admin::CourseDatesController < Admin::SharedController
  before_filter :get_course
  
  # GET /admin/courses/:course_id/course_dates
  def index 
    @course_dates = @course.course_dates.includes(:group).paginate(:page => params[:page]).order('date DESC')
  end
  
  # GET /admin/courses/:course_id/course_dates/:id
  def show
    @course_date = @course.course_dates.find(params[:id])
  end
  
  # GET /admin/courses/:course_id/course_dates/new
  def new
    @course_date = @course.course_dates.build
    @groups = Group.order(:name)
    render 'form'
  end
  
  # POST /admin/courses/:course_id/course_dates.json
  def create
    @course_date = @course.course_dates.build(params[:course_date])
    @course_date.save
    
    respond_to do |format|
      format.json { render json: { errors: @course_date.errors, url: admin_course_course_dates_url(@course) } }
    end
  end
  
  # GET /admin/courses/:course_id/course_dates/edit
  def edit
    @course_date = @course.course_dates.find(params[:id])
    @groups = Group.order(:name)
    render 'form'    
  end
  
  # PUT /admin/courses/:course_id/course_dates/:id.json
  def update
    @course_date = @course.course_dates.find(params[:id])
    @course_date.update_attributes(params[:course_date])
    
    respond_to do |format|
      format.json { render json: { errors: @course_date.errors, url: admin_course_course_dates_url(@course) } }
    end
  end
  
  # DELETE /admin/courses/:course_id/course_dates/:id.json
  def destroy
    @course_date = @course.course_dates.find(params[:id])
    
    respond_to do |format|
      format.json { render json: { deleted: @course_date.destroy } }
    end
  end
  
  protected
    def get_course
      @course = Course.active.find(params[:course_id])       
    end
end

app/helpers/admin/course_dates_helper.rb
module Admin::CourseDatesHelper
end

app/views/admin/course_dates/form.html.erb
<% content_for :head do %>
  <%= javascript_include_tag 'admin/shared/section_form' %>
  <%= javascript_include_tag 'admin/course_dates/form' %>
<% end %>
<div class="content-wrapper">
  <div id="section-actions">
    <div class="left">
      <h2><%= @course_date.new_record? ? 'Agregar Registro' : 'Editar Registro' %></h2>
    </div>
    <div class="right">
      <%= link_to admin_course_course_dates_url(@course), :class => 'btn gray-btn' do %>
          Cancelar
      <% end %>
    </div>  
    <div class="clear"></div>
  </div>
  <div class="form-wrapper section-form-wrapper">
    <%= form_for [:admin, @course, @course_date], :html => {:id => 'section-form',:class => 'custom-form section-form'} do |f| %>
      <div class="field">
        <%= f.label :date, 'Fecha' %>
        <%= f.text_field :date, :value => (@course_date.new_record? ? '' : slash_format(@course_date.date) ) %>
      </div>
      <div class="field">
        <%= f.label :group_id, 'Grupo' %>
        <%= f.select :group_id, group_options(@groups), {:prompt => 'Seleccione'}, {:class => 'wide'} %>
      </div>
      <div class="actions">
        <%= f.submit 'Continuar', :class => 'btn green-btn' %>
      </div>
    <% end %>    
  </div>
</div>

app/views/admin/course_dates/index.html.erb
<div class="content-wrapper">
  <div id="section-actions">
    <div class="left">
      <h2><%= truncate @course.name, :length => 50 %></h2>
    </div>
    <div class="right">
      <%= link_to admin_courses_url, :class => 'btn gray-btn' do %>
        Regresar
      <% end %> 
      <%= link_to new_admin_course_course_date_url(@course), :class => 'btn green-btn' do %>
        <i class="icon-plus"></i> Agregar
      <% end %>
    </div>  
    <div class="clear"></div>
  </div>
  <% if @course_dates.any? %>
    <div class="table-wrapper">
      <table class="custom-table">
        <thead>
          <tr>
            <th>Fecha</th>
            <th>Grupo</th>
            <th></th>        
            <th></th>
          </tr>        
        </thead>
        <tbody>
          <% @course_dates.each_with_index do |date,index| %>
            <%= render_table_row(index) do %>
              <td><%= slash_format date.date %></td>
              <td><%= date.group ? date.group.name : "Sin asignar" %></td>
              <td class="action">
                <%= link_to edit_admin_course_course_date_url(@course, date), 'data-tooltip' => 'Editar' do %>
                  <i class="icon-pencil"></i>
                <% end %>
              </td>
              <td class="action">
                <%= link_to admin_course_course_date_url(@course, date), 'data-tooltip' => 'Eliminar', 'data-method' => 'delete' do %>
                  <i class="icon-remove"></i>
                <% end %>
              </td>
            <% end %>
          <% end %>
        </tbody>
      </table>
    </div>  
    <%= paginate @course_dates %>  
  <% else %>
    <div class="not-found">
      No hay fechas para este curso
    </div>
  <% end %>
</div>

app/views/admin/course_dates/show.html.erb
<div class="content-wrapper">
  <div id="section-actions">
    <div class="left">
      <h2><%= @course.name %> | <%= slash_format @course_date.date %></h2>
    </div>
    <div class="right">
      <%= link_to admin_course_course_dates_url(@course), :class => 'btn gray-btn' do %>
        Regresar
      <% end %>
    </div>
    <div class="clear"></div>
  </div>
  
  <% if @course_date.enrollments.any? %>
    <div class="table-wrapper">
      <table class="custom-table">
        <thead>
          <tr>
            <th>Nombre</th>
            <th>Email</th>            
            <th>Telefono</th>
            <th>Compa&ntilde;&iacute;a</th>
          </tr>        
        </thead>
        <tbody>
          <% @course_date.enrollments.includes(:student).each_with_index do |enrollment,index| %>
            <%= render_table_row(index) do %>
              <td><%= truncate student.full_name, :length => 50 %></td>
              <td><%= student.email %></td>
              <td><%= student.phone %></td>
              <td>
                <%= content_tag :span, truncate(student.company, :length => 50), :title => student.company %>
              </td>              
            <% end %>
          <% end %>
        </tbody>
      </table>
    </div>    
  <% else %>
    <div class="not-found">
      No hay inscripciones para esta fecha
    </div>
  <% end %>
  
  
  
  
</div>