config/routes.rb
Certificatec::Application.routes.draw do
  root :to => 'splash#index'
  
  match '/login' => 'splash#login', :as => 'login'
  match '/logout' => 'splash#logout', :as => 'logout'
  match 'splash/authenticate' => 'splash#authenticate', :via => :post
  match '/cursos' => 'courses#index', :as => 'courses'
  match '/fechas' => 'courses#agenda', :as => 'agenda'
  match '/inscripcion/:group_id' => 'courses#enroll', :as => 'enroll'
  match '/contacto' => 'splash#contact', :as => 'contact'
  
  resources :students, :only => :create
  
  namespace :admin do 
    root :to => 'courses#index'
    
    resources :courses do
      resources :course_dates
      resources :exams
    end
    resources :groups
    resources :users
  end
end

app/controllers/admin/courses_controller.rb
class Admin::CoursesController < Admin::SharedController
  # GET /admin/courses
  def index
    @courses = Course.active.order(:name).paginate(:page => params[:page])
  end
  
  # GET /admin/courses/new
  def new
    @course = Course.new
    render 'form'
  end
  
  # POST /admin/courses.json
  def create
    @course = Course.new(params[:course])
    @course.save
    
    respond_to do |format|
      format.json { render json: { errors: @course.errors, url: admin_courses_url } }
    end
  end
  
  # GET /admin/courses/:id/edit
  def edit
    @course = Course.active.find(params[:id])
    render 'form'    
  end
  
  # PUT /admin/courses/:id.json
  def update
    @course = Course.active.find(params[:id])
    @course.update_attributes(params[:course])
    
    respond_to do |format|
      format.json { render json: { errors: @course.errors, url: admin_courses_url } }
    end
  end
  
  # DELETE /admin/courses/:id.json
  def destroy
    @course = Course.active.find(params[:id])
    @course.is_active = 0
    
    respond_to do |format|
      format.json { render json: { deleted: @course.save } }
    end
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  def index
    @courses = Course.active.order(:name)
  end
  
  def agenda
    @groups = Group.available.includes(:course_dates => :course, :exams => :course).order(:course_dates => :date)
  end
  
  def enroll
    @group = Group.find(params[:group_id])
    @student = Student.new
  end
end

app/helpers/admin/courses_helper.rb
module Admin::CoursesHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/admin/courses/form.html.erb
<% content_for :head do %>
  <%= javascript_include_tag 'admin/shared/section_form' %>
<% end %>
<div class="content-wrapper">
  <div id="section-actions">
    <div class="left">
      <h2><%= @course.new_record? ? 'Agregar Registro' : 'Editar Registro' %></h2>
    </div>
    <div class="right">
      <%= link_to admin_courses_url, :class => 'btn gray-btn' do %>
          Cancelar
      <% end %>
    </div>  
    <div class="clear"></div>
  </div>
  <div class="form-wrapper section-form-wrapper">
    <%= form_for [:admin, @course], :html => {:id => 'section-form',:class => 'custom-form section-form'} do |f| %>
      <div class="field">
        <%= f.label :name, 'Nombre' %>
        <%= f.text_field :name %>
      </div>
      <div class="field">
        <%= f.label :description, 'Descripci&oacute;n'.html_safe %>
        <%= f.text_area :description %>
      </div>
      <div class="actions">
        <%= f.submit 'Continuar', :class => 'btn green-btn' %>
      </div>
    <% end %>    
  </div>
</div>

app/views/admin/courses/index.html.erb
<div class="content-wrapper">
  <div id="section-actions">
    <div class="right">
      <%= link_to new_admin_course_url, :class => 'btn green-btn' do %>
        <i class="icon-plus"></i> Agregar
      <% end %>
    </div>  
    <div class="clear"></div>
  </div>
  <% if @courses.any? %>
    <div class="table-wrapper">
      <table class="custom-table">
        <thead>
          <tr>
            <th>Nombre</th>
            <th>Descripci&oacute;n</th>
            <th>Fechas disponibles</th>
            <th></th>
            <th></th>
            <th></th>        
            <th></th>
          </tr>        
        </thead>
        <tbody>
          <% @courses.each_with_index do |course,index| %>
            <%= render_table_row(index) do %>
              <td><%= truncate course.name, :length => 50 %></td>
              <td><%= truncate course.description, :length => 50 %></td>
              <td><%= course.available_dates.length %></td>
              <td class="action">
                <%= link_to admin_course_exams_url(course), 'data-tooltip' => 'Ex&aacute;menes'.html_safe do %>
                  <i class="icon-file-alt"></i>
                <% end %>
              </td>
              <td class="action">
                <%= link_to admin_course_course_dates_url(course), 'data-tooltip' => 'Fechas' do %>
                  <i class="icon-calendar"></i>
                <% end %>
              </td>
              <td class="action">
                <%= link_to edit_admin_course_url(course), 'data-tooltip' => 'Editar' do %>
                  <i class="icon-pencil"></i>
                <% end %>
              </td>
              <td class="action">
                <%= link_to admin_course_url(course), 'data-tooltip' => 'Eliminar', 'data-method' => 'delete', 'data-confirm' => 'Se eliminara el curso, sus fechas y ex&aacute;menes' do %>
                  <i class="icon-remove"></i>
                <% end %>
              </td>
            <% end %>
          <% end %>
        </tbody>
      </table>
    </div>    
    <%= paginate @courses %>
  <% else %>
    <div class="not-found">
      No hay cursos
    </div>
  <% end %>
</div>