config/routes.rb
Certificatec::Application.routes.draw do
  root :to => 'splash#index'
  
  match '/login' => 'splash#login', :as => 'login'
  match '/logout' => 'splash#logout', :as => 'logout'
  match 'splash/authenticate' => 'splash#authenticate', :via => :post
  match '/cursos' => 'courses#index', :as => 'courses'
  match '/fechas' => 'courses#agenda', :as => 'agenda'
  match '/inscripcion/:group_id' => 'courses#enroll', :as => 'enroll'
  match '/contacto' => 'splash#contact', :as => 'contact'
  
  resources :students, :only => :create
  
  namespace :admin do 
    root :to => 'courses#index'
    
    resources :courses do
      resources :course_dates
      resources :exams
    end
    resources :groups
    resources :users
  end
end

app/models/course.rb
class Course < ActiveRecord::Base
  has_many :course_dates
  has_many :exams
  
  validates_presence_of :name
  validates_length_of :name, :in => 2..100
  
  scope :active, where(:is_active => 1)
  
  def available_dates
    self.course_dates.where('date > ?', Date.today)
  end
  
end

app/models/course_date.rb
class CourseDate < ActiveRecord::Base
  belongs_to :group
  belongs_to :course
  
  scope :upcoming, where('date > ?', Date.today).order(:date)
  
end

app/models/enrollment.rb
class Enrollment < ActiveRecord::Base
  belongs_to :student
  belongs_to :group

end

app/models/exam.rb
class Exam < ActiveRecord::Base

  belongs_to :course
  belongs_to :group

  validates_presence_of :date, :location  
  
  scope :upcoming, where('date > ?', Time.now).order(:date)
  
  def minutes
    self.date.min if self.date
  end
  
  def minutes=(minutes)
    self.date = self.date.change(:min => minutes)
  end
  
  def hour
    self.date.hour if self.date
  end
  
  def hour=(hour)
    self.date = self.date.change(:hour => hour)
  end
end

app/models/group.rb
class Group < ActiveRecord::Base
  has_many :enrollments
  has_many :course_dates
  has_many :exams
  has_many :students, :through => :enrollments
  
  validates_presence_of :name, :price, :start_date
  validates_numericality_of :price
  
  scope :available, where('start_date > ?', Date.today)
  
  def to_csv
    require 'csv'
    CSV.generate do |csv| 
      csv << [self.name] << []
      csv << Student::CSV_COLUMNS
      self.students.each do |student|
        csv << student.to_csv_array
      end
    end
  end
end

app/models/student.rb
class Student < ActiveRecord::Base
  has_many :enrollments
  
  CSV_COLUMNS = ["Nombre","Apellidos","Email","Empresa","Telefono"]
  
  validates_presence_of :name, :surname, :email, :company
  
  # Returns self's full_name  
  def full_name
    "#{self.name} #{self.surname}"
  end 
  
  def to_csv_array
    [self.name, self.surname, self.email, self.company, self.phone]
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  SALT = 'c3rt1f1c4t3c!'
  
  attr_protected :encrypted_password, :password
  
  validates_presence_of [:name, :surname, :email, :encrypted_password]
  validates_confirmation_of :password, :if => :needs_password?
  validates_length_of :password, :minimum => 6, :if => :needs_password?
  validate :email_is_unique
  
  scope :active, where(:is_active => 1)
  scope :exclude, lambda { |user| where('users.id <> ?', user.id) }
  
  # Returns a user with corresponding email and password or nil
  def self.authenticate(email, pwd)
    user = self.active.where(:email => email).first
    if user
      user = nil unless user.encrypted_password.eql? self.encrypt(pwd, SALT)
    end
    user
  end
  
  # Returns the full_name of the user
  def full_name
    "#{self.name} #{self.surname}"
  end
  
  def change_password(current_password, new_password)
    if self.class.encrypt(current_password, SALT).eql? self.encrypted_password
      self.password = new_password
      self.save
    else
      errors.add(:current_password, "no coincide con el password actual")
      false
    end
  end
  
  # True if user needs to assign a password
  def needs_password?
    self.new_record? || !self.password.blank?
  end
  
  def password
    @password
  end
  
  def password=(pwd)
    @password = pwd
    self.encrypted_password = self.class.encrypt(pwd,SALT) unless pwd.blank?
  end
  
  protected
    
    def self.encrypt(*args)      
      Digest::SHA1.hexdigest(args.join)
    end
    
    # Validates that the email is unique per active users
    def email_is_unique
      active_users = User.active.where(:email => self.email)
      active_users = active_users.exclude(self) unless self.new_record?
      errors.add :email, 'ya existe' if active_users.count(:id) > 0
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  protected
    def get_current_user
      unless session[:user_id].blank?
        @current_user = User.select([:id, :name, :surname, :email]).find(session[:user_id])    
      end
    end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  def index
    @courses = Course.active.order(:name)
  end
  
  def agenda
    @groups = Group.available.includes(:course_dates => :course, :exams => :course).order(:course_dates => :date)
  end
  
  def enroll
    @group = Group.find(params[:group_id])
    @student = Student.new
  end
end

app/controllers/splash_controller.rb
class SplashController < ApplicationController
  def index
    @upcoming_dates = CourseDate.upcoming.includes(:course).where(:courses => {:is_active => 1}).limit(5)
    @upcoming_exam = Exam.upcoming.limit(1).first
  end
  
  def login
    render layout: 'login'
  end
  
  def logout
    reset_session
    flash[:notice] = 'Tu sesi&oacute;n ha terminado'
    redirect_to root_url
  end
  
  def authenticate
    @user = User.authenticate(params[:login][:email], params[:login][:password])
    if @user
      session[:user_id] = @user.id
      redirect_to admin_root_url
    else
      flash[:notice] = 'Usuario / Contrase&ntilde;a inv&aacute;lida'
      render :login, layout: 'login'
    end
  end
  
  def contact
    
  end
  
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  def create
    @student = Student.new(params[:student])
    
    if @student.save
      enrollment = @student.enrollments.build(group_id: params[:group_id])
      enrolled = enrollment.save
      if enrolled
        Notifier.enroll(@student.id, params[:group_id]).deliver
      end 
    end
    
    respond_to do |format|
      format.json { render json: { errors: @student.errors, enrolled: enrolled } }
    end
  end
end

app/helpers/admin/courses_helper.rb
module Admin::CoursesHelper
end

app/helpers/admin/exams_helper.rb
module Admin::ExamsHelper
end

app/helpers/admin/groups_helper.rb
module Admin::GroupsHelper
end

app/helpers/admin/shared_helper.rb
module Admin::SharedHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  MONTHS = [
    {:short => 'Ene', :long => 'Enero'},
    {:short => 'Feb', :long => 'Febrero'},
    {:short => 'Mar', :long => 'Marzo'},
    {:short => 'Abr', :long => 'Abril'},
    {:short => 'May', :long => 'Mayo'},
    {:short => 'Jun', :long => 'Junio'},
    {:short => 'Jul', :long => 'Julio'},
    {:short => 'Ago', :long => 'Agosto'},
    {:short => 'Sep', :long => 'Septiembre'},
    {:short => 'Oct', :long => 'Octubre'},
    {:short => 'Nov', :long => 'Noviembre'},
    {:short => 'Dic', :long => 'Diciembre'}
  ]

  def slash_format(date)
    date.strftime("%d/%m/%Y")
  end
  
  def text_format(date)
    "#{date.day} de #{MONTHS[date.month][:long]} de #{date.year}"
  end
  
  def short_month(date)    
    MONTHS[date.month - 1][:short]
  end
  
  def time_format(date)
    date.strftime("%H:%M")
  end
  
  def hour_of_day(date)
    date.strftime("%I")
  end
  
  def long_month(date)
    MONTHS[date.month - 1][:long]
  end
  
  def hour_options
    (0..23).to_a
  end
  
  def minute_options
    (0..60).to_a
  end
  
  def nav_link(text, path)
    class_name =  current_page?(path) ? 'active' : ''
    link_to text, path, :class => class_name
  end
  
  def render_table_row(index)
    if index.odd?
      content_tag :tr, :class => 'alt' do
          yield
      end
    else
      content_tag :tr do
          yield
      end
    end
  end
  
  def paginate(collection)
    will_paginate collection, :previous_label => '&#8592; Anterior', :next_label => 'Siguiente &#8594;'
  end
  
  def group_options(groups)
    groups.map do |group|
      [group.name, group.id]
    end
  end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/splash_helper.rb
module SplashHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Certificatec | Admin</title>
    
    <%= javascript_include_tag 'lib/jquery-1.9.1.min' %>
    <%= javascript_include_tag 'lib/jquery-ui-1.10.3.custom.min' %>
    <%= javascript_include_tag 'lib/jquery.tipsy' %>
    <%= javascript_include_tag 'plugins/fmx_form' %>
    <%= javascript_include_tag 'plugins/fmx_dialog' %>
    <%= javascript_include_tag 'admin' %>
    
    <%= stylesheet_link_tag 'reset' %>
    <%= stylesheet_link_tag 'http://fonts.googleapis.com/css?family=Open+Sans:400,300' %>
    <%= stylesheet_link_tag 'font-awesome.min' %>
    <%= stylesheet_link_tag 'lib/tipsy' %>
    <%= stylesheet_link_tag 'lib/jquery-ui-1.10.3.custom.min' %>
    <%= stylesheet_link_tag 'plugins/fmx_form' %>
    <%= stylesheet_link_tag 'plugins/fmx_dialog' %>
    <%= stylesheet_link_tag 'certificatec' %>
    <%= stylesheet_link_tag 'admin' %>
    <%= csrf_meta_tag %>
    <script type="text/javascript">
      (function(){
        $(function(){
          certificatec.init();
        });
      })(jQuery);
    </script>
    <%= yield :head %>
    
  </head>
  <body>
    <div id="header">
      <div class="content-wrapper">
        <div id="tec-logo" class="left"></div>          
        <div id="certification-center" class="left">
          <h1>| Administraci&oacute;n</h1>
        </div>  
        <div id="user-info" class="right">
          <span><%= @current_user.full_name %></span>
          <span><%= link_to 'Salir', logout_url, :class => 'inline-link' %></span>
        </div>      
        <div class="clear"></div>
      </div>  
    </div>
    <div id="navbar">
      <div class="content-wrapper">
        <%= nav_link 'Cursos', admin_courses_url %>
        <%= nav_link 'Grupos', admin_groups_url %>
        <%= nav_link 'Administradores', admin_users_url %>
      </div>  
    </div>
    <%= yield %>    
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Certificatec</title>
    <%= stylesheet_link_tag 'reset' %>
    <%= stylesheet_link_tag 'http://fonts.googleapis.com/css?family=Open+Sans:400,300' %>
    <%= stylesheet_link_tag 'certificatec' %>
    <%= csrf_meta_tag %>
    <%= favicon_link_tag 'favicon.ico' %>
    <%= yield :head %>
  </head>
  <body>
    <% if flash[:notice] %> 
      <div id="flash"><%= flash[:notice].html_safe %></div>
    <% end %>
    <div id="header">
      <div class="content-wrapper">
        <div id="tec-logo" class="left"></div>          
        <div id="certification-center" class="left">
          <h1>Centro de certificaci&oacute;n</h1>
        </div>
        <div id="contact-info" class="right">
          Instituto Tecnológico y de Estudios Superiores de Monterrey<br />
          Dr. Javier Cuevas Ordaz<br />
          E-mail: <a href="mailto:fcuevas@itesm.mx" class="inline-link">fcuevas@itesm.mx</a> <br />
          (+52) 55 91778104 
        </div>
        <div class="clear"></div>
      </div>  
    </div>
    <div id="navbar">
      <div class="content-wrapper">
        <%= nav_link 'Inicio', root_url %>
        <%= nav_link 'Acerca de los cursos', courses_url %>
        <%= nav_link 'Fechas de los cursos', agenda_url %>
        <%= nav_link 'Ubicaci&oacute;n'.html_safe, contact_url %>
      </div>  
    </div>
    <%= yield %>
    <div id="footer">
      <div class="content-wrapper">
        <div id="footer-navigation" class="left">
          <h3>Navegaci&oacute;n</h3>
          <%= link_to 'Inicio', root_url %> <br />          
          <%= link_to 'Acerca de los cursos', courses_url %> <br />
          <%= link_to 'Fechas de los cursos', agenda_url %> <br />
          <%= link_to 'Ubicaci&oacute;n'.html_safe, contact_url %>
        </div>
        <div id="google-logo" class="right"></div>
        <div class="clear"></div>
      </div>
    </div>
    <div id="privacy">
      <div class="content-wrapper">
        <%= link_to 'Google', '#', :class => 'inline-link' %>
        <%= link_to 'Aviso de Privacidad', '#', :class => 'inline-link' %>
      </div>  
    </div>
  </body>
</html>

app/views/layouts/login.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Certificatec</title>
    <%= stylesheet_link_tag 'reset' %>
    <%= stylesheet_link_tag 'http://fonts.googleapis.com/css?family=Open+Sans:400,300' %>
    <%= stylesheet_link_tag 'certificatec' %>
    <%= csrf_meta_tag %>
    <%= yield :head %>
  </head>
  <body>
    <% if flash[:notice] %> 
      <div id="flash"><%= flash[:notice].html_safe %></div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/layouts/notifier.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>Certificatec</title>
    </head>
    <body>
    	<table align="center" border="0" cellpadding="0" cellspacing="0" width="600">
    		<!-- START HEADER -->
    		<tr style="padding: 10px 20px 10px 20px; background: #fafafa; height: 80px;">    		  
    		  <td>
    		    <%= image_tag attachments['logo.png'].url %>
    		  </td>
    			<td style="margin: 0 0 0 10px;">
            <%= yield :title %>  
    			</td>
    		</tr>
    		<!-- END HEADER -->
    		<!-- START CONTENT -->
    		<tr>
    			<td colspan="2" style="background: #FFFFFF; padding: 20px 20px 20px 20px; font-family: Arial,Helvetica,sans-serif; font-size: 1em; text-align:left;">
    				<%= yield %>
    			</td>
    		</tr>    		
    		<tr>
    			<!-- START DISCLAIMER -->
  				<td colspan="2" style="background: #F9F9F9; font-family: Arial,Helvetica,sans-serif; font-size: 0.7em; text-align: justify; color: #444444; padding: 20px 20px 30px 20px;">
            <p>
              Este mensaje contiene informacion confidencial y se entiende dirigido y para uso exclusivo del destinatario. Si recibes este mensaje y no eres el destinatario por favor eliminalo, ya que difundir, revelar, copiar o tomar cualquier accion basada en el contenido esta estrictamente prohibido.            
            </p>                    
          </td>
          <!-- END DISCLAIMER -->
    		</tr>
    		<!-- END CONTENT -->    		
    	</table>
    </body>
</html>

app/views/notifier/enroll.html.erb
<% content_for :title do %>
  <h1>Bienvenido a Certificatec</h1>
<% end %>
<p>
  Estimado: <span style="color: #0085EE;"><%= @student.full_name %></span> <br />


  Te has registrado para el grupo: <span style="color: #0085EE;"><%= @group.name %></span>
  <br />
  <br />
  <br />
  Te sugerimos vayas estudiando los temas en <%= link_to 'la ayuda para GCP de Google', 'https://support.google.com/adwords/certification/?hl=es&rd=1' %> referidos a tu curso seleccionado para venir preparado al curso. También te pedimos que sigas la página <%= link_to 'Aprende con Google', 'https://plus.google.com/u/0/+GoogleParaTuNegocio' %> donde tienes toda la información de cursos y educación en la región. Y si eres de los que son ambiciosos y proactivos, siempre puedes aprender más en <%= link_to 'Agency Edge', 'https://www.google.com/partners' %> donde tienes casos de éxito, monografías, estudios, cursos, webinars y muchas otras cosas. 
  <br />
  <br />
  Estimado usuario, el haberte registrado en este sitio no implica tu aceptación al curso, está solo será efectiva en el momento que tramites tu pago a través del sitio oficial del <%= link_to 'Tecnológico de Monterrey', 'http://csa.itesm.mx:8080/FichaDePagoCol/index.jsp' %> sigue los pasos siguientes: Pago de Servicio>Nombre>Generar>Campus Santa Fe>Certificación>Certificación Google Adwords. &iexcl;Gracias!
  <br />
  <br />
  Despu&eacute;s de concretar el pago, por favor responde a este correo con tu comprobante de pago, ya sea con una impresi&oacute;n de pantalla o una copia escaneada del comprobante. La fecha l&iacute;mite para realizar tu pago es el <%= text_format(@group.start_date) %>
  <br />
  <br />  
  &iexcl;Un saludo y nos vemos pronto! 
  <br />
  <br />
  <br />
  Atentamente
  Equipo de certificadores del Tecnológico de Monterrey Campus Santa Fe.
</p>